### PR TITLE
Simultaneously supporting Python2 & Python3

### PR DESCRIPTION
**Pull request by willwebberley**
Small updates to imports and other areas to improve cross-compatibility between Python2 and Python3.

Also fixed a couple of bugs in division and multiplication, where the currency was not being correctly converted before operated upon.

### CODE REVIEW

**Comment by ashokfernandez** [comment]
Nice additions @flyingsparx, thanks for contributing!

**Comment by ashokfernandez** [comment]
Added credit to README

**Comment by willwebberley** [comment]
No problem - it's a great little library that we've found very useful!

**Comment by willwebberley** [comment]
@ashokfernandez Also, thanks very much for the credit! If you get the time, is there any chance you update it so that it also references the company I'm from in addition? (e.g. "[Will Webberley](https://github.com/flyingsparx) from [Chaser](https://www.chaser.io/) for adding..."). Thanks!

**Comment by ashokfernandez** [comment]
Done!

**Comment by willwebberley** [comment]
@ashokfernandez Thank you!

**Pull request merged**
